### ISSUE TITLE
Builds failing randomly: `panic: runtime error: makeslice: len out of range`

### ISSUE THREAD

**Issue by amulware** [bitrise-io/bitrise#431]
We've recently (starting ~28 hours ago) been getting a lot of (randomly) failing builds. The error always happens in the xcode-test step (version 1.17.1), while constructing the step-footer for the log.
Rerunning the build usually makes it succeed.

From the error output in the log, it seems the problem is in [print.go:getRunningStepFooterMainSection()](https://github.com/bitrise-io/bitrise/blob/master/bitrise/print.go#L200).

The error happens inside one of the `strings.Repeat` calls which used to be in line 246 (mentioned in the log) but is now in [line 255](https://github.com/bitrise-io/bitrise/blob/master/bitrise/print.go#L255).

Here is the end of our logs, including stack trace:
```
▸ Test Succeeded
|                                                                              |
+----+--------------------------------------------------------------+----------+
panic: runtime error: makeslice: len out of range [recovered]
	panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
panic(0x3ad360, 0xc420456120)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli.HandleAction.func1(0xc4201a7958)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli/app.go:478 +0x247
panic(0x3ad360, 0xc420456120)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
strings.Repeat(0x408ef0, 0x1, 0xfffffffffffffffe, 0x2, 0x2)
	/usr/local/Cellar/go/1.7.1/libexec/src/strings/strings.go:420 +0x49
github.com/bitrise-io/bitrise/bitrise.getRunningStepFooterMainSection(0xc420379180, 0xa, 0xc42010be80, 0x11, 0xc42037918a, 0x6, 0xc420379190, 0x6, 0x0, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/bitrise/print.go:246 +0x640
github.com/bitrise-io/bitrise/bitrise.PrintRunningStepFooter(0xc420379180, 0xa, 0xc42010be80, 0x11, 0xc42037918a, 0x6, 0xc420379190, 0x6, 0x0, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/bitrise/print.go:515 +0x3ed
github.com/bitrise-io/bitrise/cli.activateAndRunSteps.func1(0xc4201580f0, 0xc420158120, 0xc420158150, 0xc420158180, 0xc4201581b0, 0xc4201581e0, 0xc4201564c0, 0xc4202d6800, 0x32, 0xc4202d4c60, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/run_util.go:517 +0x3a9
github.com/bitrise-io/bitrise/cli.activateAndRunSteps(0xc4200f0888, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc42012ac70, 0x1, 0x1, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/run_util.go:798 +0x1314
github.com/bitrise-io/bitrise/cli.runWorkflow(0xc4200f0888, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc42012ac70, 0x1, 0x1, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/run_util.go:810 +0x1e7
github.com/bitrise-io/bitrise/cli.activateAndRunWorkflow(0xc4200f0888, 0x4, 0xc4200f0888, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc42012ac70, 0x1, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/run_util.go:832 +0x33b
github.com/bitrise-io/bitrise/cli.runWorkflowWithConfiguration(0xecf9be495, 0x1ab8c5c7, 0x5e35c0, 0xc4200f0888, 0x4, 0xc42012a318, 0x5, 0xc420015980, 0x31, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/run_util.go:935 +0x740
github.com/bitrise-io/bitrise/cli.runAndExit(0xc42012a318, 0x5, 0xc420015980, 0x31, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/run.go:106 +0x122
github.com/bitrise-io/bitrise/cli.run(0xc420088c80, 0x0, 0x0)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/run.go:215 +0x94c
reflect.Value.call(0x39bec0, 0x446d50, 0x13, 0x4093eb, 0x4, 0xc4201a7918, 0x1, 0x1, 0x11b208, 0x3ff300, ...)
	/usr/local/Cellar/go/1.7.1/libexec/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x39bec0, 0x446d50, 0x13, 0xc4201a7918, 0x1, 0x1, 0x5e4580, 0xc4200d5908, 0x123e76)
	/usr/local/Cellar/go/1.7.1/libexec/src/reflect/value.go:302 +0xa4
github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli.HandleAction(0x39bec0, 0x446d50, 0xc420088c80, 0x0, 0x0)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli/app.go:487 +0x1e0
github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli.Command.Run(0x409271, 0x3, 0x0, 0x0, 0x5d81d0, 0x1, 0x1, 0x4121ef, 0x1a, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli/command.go:191 +0xc3b
github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli.(*App).Run(0xc4200ec000, 0xc42000c0a0, 0xa, 0xa, 0x0, 0x0)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli/app.go:240 +0x611
github.com/bitrise-io/bitrise/cli.Run()
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/cli.go:157 +0x1b0
main.main()
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/main.go:6 +0x14
Command failed: exit status 2
```

Hope this is useful. Let me know if any other information is needed.

**Comment by amulware** [comment]
Looking into the code more, it seems the problem (calling strings.Repeat with a negative parameter) is actually already fixed by e8510f3d42424d2d93e1dd165a4f097b862c5d3f.

So there is that. :D

**Comment by viktorbenei** [comment]
Thanks for the detailed error report!

You're right, we'll release a new CLI version next week with the fix and update the VMs ;)

**Comment by viktorbenei** [comment]
Fixed in https://github.com/bitrise-io/bitrise/pull/429
